export const ADD_FAVORITE = "ADD_FAVORITE";
export const DELETE_FAVORITE = "DELETE_FAVORITE";
export const ADD_CHARACTERS = "ADD_CHARACTERS";
export const DELETE_CHARACTER = "DELETE_CHARACTER";
export const CHARACTER_NAVIGATE = "CHARACTER_NAVIGATE";